### ISSUE TITLE
GraphQL: index user initiated balance transfer events

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_graphql#1]
In order to get a complete view of their wallet activity, users need to be able to see balance transfers that they've initiated manually, in addition to bridge and contract billing transactions.

Propose: index all balance transfer events, or if possible, filter those that are not associated with bridge/contract functions since that data is already available in billing/mint/burn reports.

**Comment by DylanVerstraete** [comment]
Transfer events are already indexed AFAIK, it's under `HistoricalBalances`

**Comment by scottyeager** [comment]
Yes, balance updates are provided, but I don't think there's information included about the transaction counterparty. Desired functionality would be to identify the source and destination of every transaction associated with a given wallet address.

**Comment by DylanVerstraete** [comment]
Technically speaking you could assemble this, but it will be a hard task. I will see if I can index transfer events that just simply index (from, to, amount, time) which is enough information to create a historical overview.

**Comment by scottyeager** [comment]
Sounds good! Thank you.

**Comment by scottyeager** [comment]
https://github.com/threefoldtech/tfchain_graphql/issues/11
