### ISSUE TITLE
two accounts with the same id

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfchain_graphql#100]
i have two accounts with same id
and they have different relays this should not be possible . 
![image](https://user-images.githubusercontent.com/110984055/225013926-34752650-0e01-48a7-a1cb-f094b63e2540.png)

**Comment by DylanVerstraete** [comment]
Network?

**Comment by DylanVerstraete** [comment]
![image](https://user-images.githubusercontent.com/17138347/232465606-91667318-ba05-4e8c-a260-ddd14d5109e6.png)

Fixed on QA and also on other networks
