### ISSUE TITLE
Track node GPU status events

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#104]
see https://github.com/threefoldtech/tfchain/issues/737

**Comment by mohamedamer453** [comment]
Verified on devnet.

Nodes with gpus can be queried using `hasGpu_eq` flag. and also the `extraFee` can be returned in the `nodes` query.

![image](https://github.com/threefoldtech/tfchain_graphql/assets/101194226/eaf16062-878e-4071-8221-6a862378fe32)
