### ISSUE TITLE
document running in production mode

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_graphql#111]
https://github.com/threefoldtech/tfchain_graphql/blob/master/docs/production.md

**Comment by DylanVerstraete** [comment]
added here https://github.com/threefoldtech/tfchain_graphql/blob/8687ee51951423eee0bb38ebe81ba6bff67ac4eb/docs/production.md

**Comment by mohamedamer453** [comment]
Verified.

Running in production mode docs were added in https://github.com/threefoldtech/tfchain_graphql/blob/master/docs/production.md
