### ISSUE TITLE
complete typeChanges.md documentation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_graphql#112]
https://github.com/threefoldtech/tfchain_graphql/blob/master/docs/typeChanges.md

**Comment by DylanVerstraete** [comment]
addressed here https://github.com/threefoldtech/tfchain_graphql/pull/123

**Comment by mohamedamer453** [comment]
Verified from https://github.com/threefoldtech/tfchain_graphql/blob/master/docs/typeChanges.md

The docs were updated, and the `todo` sections in the docs were completed.
