### ISSUE TITLE
update the development.md docs to use the Makefile

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_graphql#115]
the makefile in the repo should drive the [development flow](https://github.com/threefoldtech/tfchain_graphql/blob/8f8c245e07b0a9332ba23eead81b13ed03a5be01/docs/development.md)

**Comment by DylanVerstraete** [comment]
I suggest we remove this makefile since the template project (that we cloned) https://github.com/subsquid-labs/squid-substrate-template#squid-template-project also is not using it anymore. I hardly see makefiles being used in js/ts projects.
