### ISSUE TITLE
src: document the code structure and flow

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_graphql#121]
![image](https://github.com/threefoldtech/tfchain_graphql/assets/64129/fb91a580-e122-4b40-9406-74902d5feb51)

- types, typesDevnet, typesLocal usage
- models and mappings? 
  -   seems the models is generated directly from the substrate types?
  -  and mapping is ?

please make sure to clarify these items in a markdown file

**Comment by DylanVerstraete** [comment]
added in https://github.com/threefoldtech/tfchain_graphql/blob/8687ee51951423eee0bb38ebe81ba6bff67ac4eb/README.md#project-layout

**Comment by sameh-farouk** [comment]
Verified: Project structure was added to docs
