### ISSUE TITLE
Processor down on mainnet

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_graphql#13]
Processor: 
![image](https://user-images.githubusercontent.com/88312671/153166951-0ea8124f-0ee3-4831-bd65-f5747649f155.png)

querynode:
![image](https://user-images.githubusercontent.com/88312671/153167136-1980eb89-b6c3-4f96-b79a-b9a10aabe472.png)

**Comment by coesensbert** [comment]
https://github.com/threefoldtech/tf_operations/issues/667

**Comment by DylanVerstraete** [comment]
Fixed
