### ISSUE TITLE
Contracts hash and data are not updated

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfchain_graphql#142]
## Description

On contract update event deployment data and deployment hash are not updated and stored, they remain the same as before the update.
For example:
Contract 50401 on devnet:
https://gridproxy.dev.grid.tf/contracts/50401
It shows a hash of `d74277ebc9bc1be9a7681a27dfca525a` while querying the chain shows a hash of `95c3dee2b592ee9b92b909691d451f9f`
After investigation with @sameh-farouk it turned out the processor ignores these changes for some reason [here](https://github.com/threefoldtech/tfchain_graphql/blob/master/src/mappings/contracts.ts#L187-L196) while it should set the data from the update event.

**Comment by sameh-farouk** [comment]
close as duplicated https://github.com/threefoldtech/tfchain_graphql/issues/135
