### ISSUE TITLE
Mismatch between graphql data and whereisip

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfchain_graphql#148]
Naming of country `czechia` comes from `whereisip` however graphql return another naming `Czech Republic`

![image](https://github.com/threefoldtech/tfchain_graphql/assets/31689104/84448a2d-e763-46d3-9af6-8ed30fd3a0ae)

![image](https://github.com/threefoldtech/tfchain_graphql/assets/31689104/bda5ccf2-d869-4f0c-a0f2-e357a798a3a6)

**Comment by samaradel** [comment]
Similar case for ```United States``` and ```United Kingdom```
![image](https://github.com/threefoldtech/tfchain_graphql/assets/11662805/59e6d785-ec36-4d80-b2a5-c1d3ca4e8777)
![image](https://github.com/threefoldtech/tfchain_graphql/assets/11662805/6a05918b-eca3-4cda-b94b-e6013b36d0ba)

**Comment by sameh-farouk** [comment]
Our squid processor uses this API `https://restcountries.com/v2/all` to initialize the countries table. country names have differences. can we show the country's name in UI but rely instead on the country code?

**Comment by sameh-farouk** [comment]
There is a v3 of the API that we are using in Graphql (currently we are using v2).
The name becomes an object that contains a common name (looks like what you want) and an official name (similar to the one we are using ATM). For example `United Kingdom` name-value looks like this
```
{ 
common": "United Kingdom",
"official": "United Kingdom of Great Britain and Northern Ireland",
...
}
```

and for `Czechia`

```
{
common": "Czechia",
"official": "Czech Republic",
...
}

so, I can switch from v2 to v3 in Graphql init script and use the common name. This would solve the reported instances from @MohamedElmdary and @samaradel  but I am not sure if there is an easy way to retrieve all country names from the `whereisip` API to verify that we won't have another mismatch.

**Comment by Omarabdul3ziz** [comment]
hi, i was debugging an issue on gridproxy https://github.com/threefoldtech/tfgrid-sdk-go/issues/699 it shows a broken region filter for nodes.


how the region filter work on the proxy?
we join the node table with the country table based on the condition `node.country` = `country.name` 

but looks like there is an inconsistency between the data returned from the graphql the common short name is the one used on the node table but the official full name is used on the country table 
![image](https://github.com/threefoldtech/tfchain_graphql/assets/32527347/515a9fa7-b9ed-45c4-9cb3-63f7e80d2712)

so that is why `/nodes?region=americas` doesn't list the `united states`d nodes. same with the United Kingdom and Czechia

**Comment by sameh-farouk** [comment]
Update:
[PR](https://github.com/threefoldtech/tfchain_graphql/pull/158) is ready for review. 

It is based on the changes I mentioned in my previous [comment](https://github.com/threefoldtech/tfchain_graphql/issues/148#issuecomment-1925874389). 

As I mentioned in the PR description, this is a temporary, easy workaround fix.
However, although it should resolve the mismatch for the reported countries, it is important to note that this fix may not work for all countries as the process of joining data from different APIs based on country names is not reliable.

To elaborate, in our squid processor, we fetch cities from the repository available at https://raw.githubusercontent.com/shivammathur/countrycity/master/data/geo.json and countries from the https://restcountries.com/ API. We then join these data based on the country name. Similarly, in the Gridproxy, we fetch node data from the chain and county data from GraphQL and join it based on the country name.

This process is not always accurate as there are often alternative spellings for country names. Hence, unless you are using the same data source, it's not guaranteed to find a match.

To properly resolve this issue, I suggest using the same API (if possible), or a more unique identifier such as country code. Also, we could sort to craft our data source and use it.
However, this would require changes in multiple services. hence I'm offering this as a temporary solution for now.

**Comment by sameh-farouk** [comment]
All is good now? @MohamedElmdary @samaradel @Omarabdul3ziz
