### ISSUE TITLE
some farm pricing policies are out of sync on mainnet

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfchain_graphql#160]
checking graphql gives some farms with policy id = 0

![image](https://github.com/threefoldtech/tfchain_graphql/assets/32527347/ad83bfdd-8111-4b36-bb94-8bcf03a0ce9b)

where checking the chain it have policy id = 1
![image](https://github.com/threefoldtech/tfchain_graphql/assets/32527347/fae873f7-b490-4653-97c2-4a23f033294e)

**Comment by sameh-farouk** [comment]
duplicated:
https://github.com/threefoldtech/tfchain_graphql/issues/96
