### ISSUE TITLE
Inconsistent country name in the nodes

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/tfchain_graphql#3]
we have inconsistency in the data coming from graphql, in the `country` field.
sometimes two letters code for the country and other times the full name
![image](https://user-images.githubusercontent.com/46320202/145399991-7b6e89a2-44ed-48f8-919d-7488ba89b6bc.png)

**Comment by DylanVerstraete** [comment]
@muhamadazmy should be fixed right?
