### ISSUE TITLE
New testnet nodes not registering on TF Chain

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_graphql#45]
I just booted a new node on testnet. On screen, it appears all systems go as seen below, but the node is not visible in the explorer or portal after several hours. Another farmer noticed the same behavior on testnet last week.

![B8C26294-E09E-4600-8ECB-4D6EDC071D0B](https://user-images.githubusercontent.com/17682591/178413182-e87258cb-ac07-4287-a100-5e863f4e671d.jpeg)

**Comment by scottyeager** [comment]
Thanks for looking into this @muhamadazmy. I didn't think to check elsewhere, but will make a note to query the chain directly in case of any issue like this in the future.

**Comment by DylanVerstraete** [comment]
I just encountered the same issue

**Comment by DylanVerstraete** [comment]
Fixed on https://github.com/threefoldtech/tfchain_graphql/tree/fix_processor , currently syncing a new one against testnet. Will close when it's done

**Comment by DylanVerstraete** [comment]
Redeployed and Fixed! thx @coesensbert
