### ISSUE TITLE
Contract state returns null

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfchain_graphql#48]
Attempting to query contracts and display their state, on mainnet:

![image](https://user-images.githubusercontent.com/17682591/183830065-820b1f71-1049-4342-9310-59d867606be2.png)

**Comment by DylanVerstraete** [comment]
Fix deployed on mainnet and testnet, it will take around 1 day to be fully working (needs to sync from block 0). Will close this issue when the graphql is synced.

**Comment by DylanVerstraete** [comment]
@scottyeager fixed is deployed and should be working again!
