### ISSUE TITLE
Explorer is not showing certification type 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfchain_graphql#54]
Field is empty. Might have something to do with threefoldtech/tfchain_explorer#232 ?

**Comment by mohamedamer453** [comment]
Verified on devnet.

all the nodes on devnet now show a Certification Type.

![image](https://user-images.githubusercontent.com/101194226/187082398-90122215-7f8d-4517-854d-aa9c6bd49221.png)

and it shows `NotCertified` if there's no certification instead of showing `None`
