### ISSUE TITLE
processor crash devnet

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#55]
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, assert_1.default)(this.isV59)

    at SmartContractModuleContractGracePeriodStartedEvent.get asV59 [as asV59] (/squid/lib/types/events.js:242:30)
    at contractGracePeriodStarted (/squid/lib/mappings/contracts.js:316:114)
    at /squid/lib/processor.js:52:127
    at /squid/node_modules/@subsquid/substrate-processor/lib/processor.js:190:35
    at /squid/node_modules/@subsquid/substrate-processor/lib/db.js:69:19
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by mohamedamer453** [comment]
New data not appearing on graphql, for example.

Node 49 on devnet can be queried from the chain and it returns full node data

![image](https://user-images.githubusercontent.com/101194226/187083233-a3a92486-57e3-4089-b925-63091d654467.png)

but on graphql it returns nothing

![image](https://user-images.githubusercontent.com/101194226/187083290-b9e0e7ec-0b57-4d87-809f-8a4d377641d3.png)

**Comment by mohamedamer453** [comment]
Verified in #56 graphql is back and working and the new node that didn't appear yesterday is now available in graphql and also on the dashboard.

![image](https://user-images.githubusercontent.com/101194226/187202488-047a6971-232f-4c1a-b429-73b147021b51.png)
