### ISSUE TITLE
New node online not available on dashboard or play Dev net 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/tfchain_graphql#56]
Bringing node 49 farm 59 online 

the node is showing online, no console errors, it accepted a new public config which is 

162.205.240.250/25 addr
162.205.240.25 gw
2600:1700:c1e0:1150:1658:d0ff:fe44:fac9/64 addr
2600:1700:c1e0:1150::1 gw
Libra.tfcloud.us domain

both the public ipv4 and ipv6 are pingable aswell as the dmz address within the local network. 

node has 2 gigabit links 
bnx1 & bnx2 are in use
-both showed successful gigabit tests during boot .

**Comment by DylanVerstraete** [comment]
fixed in https://github.com/threefoldtech/tfchain_graphql/releases/tag/2.5.10

**Comment by mohamedamer453** [comment]
Verified on devnet.

The node now appears in graphql 

![image](https://user-images.githubusercontent.com/101194226/187202072-9abe9de2-52b9-4ae4-8ab0-34d97e490f4a.png)

and also available on the dashboard.

![image](https://user-images.githubusercontent.com/101194226/187201917-35ce7692-7753-4c63-ac25-8288a77a7738.png)

![image](https://user-images.githubusercontent.com/101194226/187202004-0e09d5ce-6a82-41aa-b360-8c5eb2b03993.png)
