### ISSUE TITLE
Discrepancies graphQL

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/tfchain_graphql#6]
Some nodes are missing:

Searching for all nodes that belong to the farm 9, i got the following
query MyQuery {
  nodes(where: {farmId_eq: 9}) {
    farmId
    twinId
    nodeId
    version
  }
}
———————-
{
  "data": {
    "nodes": [
      {
        "farmId": 9,
        "twinId": 113,
        "nodeId": 75,
        "version": 35
      }
    ]
  }
}
this is right, GEC has just 1 node in that farm. But, if i retrieve all nodes without the where condition i get all nodes in all farms (useful if i am performing queries using just json), but the node aforementioned is missing.

i found other discrepancies, for example with the farm GEC-Vienna1-testnet3 (id=6)

**Comment by DylanVerstraete** [comment]
@gmachtel still an issue?

**Comment by gmachtel** [comment]
No can be closed. Thx !
