### ISSUE TITLE
Align to new power management features

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#65]
Events that changed:

- `SmartContractModule.ContractCreated`
- `SmartContractModule.ContractUpdated`

New Events:

- `TfgridModule.PowerStatusChanged`
- `TfgridModule.PowerTargetChanged`

@brandonpille am I missing anything else (I ignored group events because they are not relevant)

**Comment by brandonpille** [comment]
ContractCreated and ContractUpdated were not changed. Or do you mean when we emit them?

**Comment by brandonpille** [comment]
There is also CapacityReservationContractCanceled and DeploymentContractCanceled that were created.
