### ISSUE TITLE
update subsquid graphql version 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfchain_graphql#69]
apparently that was the reason mainnet stopped syncing yesterday?

PS: milestone needs to be updated

**Comment by DylanVerstraete** [comment]
> apparently that was the reason mainnet stopped syncing yesterday?
> 
> PS: milestone needs to be updated

The reason mainnet stopped syncing: https://github.com/threefoldtech/tfchain_graphql/issues/70

Can be solved if we progress on updating to graphql V5 or monitor the network better.

**Comment by DylanVerstraete** [comment]
Moved to 3.8.1 because of #70

**Comment by despiegk** [comment]
there is bug & monitoring solution
