### ISSUE TITLE
Indexer stops syncing when network issues occur

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#70]
Known issue on graphql indexer V4

We've seen this on last week on mainnet and devnet

**Comment by DylanVerstraete** [comment]
Can be fixed by restarting the indexer

**Comment by robvanmieghem** [comment]
Indexer should be added to the monitoring and if the block does not increase for 10 minutes, escalate

**Comment by robvanmieghem** [comment]
Since it will be covered in the monitoring and there is a fix when this should happen, I'm moving this issue to 3.8.1
