### ISSUE TITLE
QAnet indexer always stops syncing

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfchain_graphql#75]
![image](https://user-images.githubusercontent.com/88312671/211329696-9b5d5cb3-7985-4de3-8214-fad7cc335c3c.png)

**Comment by LeeSmet** [comment]
Is the node it's connected to in sync?

**Comment by coesensbert** [comment]
yes, already tried to restart the pub node a few times. It's also reachable via https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftfchain.qa.grid.tf#/explorer

![image](https://user-images.githubusercontent.com/88312671/211338218-527345f9-4946-4fa2-96d0-e418196dd28e.png)

**Comment by xmonader** [comment]
can this now be closed?

**Comment by coesensbert** [comment]
The old indexer keeps stopping, but the new one (firesquid) seems ok. For devnet, firesquid is already exposed at https://graphql.dev.grid.tf/graphql which seems to be ok, so i can do the same for qa-net @DylanVerstraete ?

@xmonader do we then incldue firesquid + cockroach db in 3.8.1 ?

**Comment by Mahmoud-Emad** [comment]
verified on qanet:
all nodes are up for a while without any problems

![image](https://user-images.githubusercontent.com/57001890/214600996-bd0d28f7-41f4-4e9f-806a-194b3b3375d6.png)

also, the `createdAt`, `updatedAt`, and `uptime` fields work well as expected!
* Node 2 :
  - created 
 
      ![image](https://user-images.githubusercontent.com/57001890/214601734-a3443fd8-02b6-4937-b309-6f765a2f2693.png)
  - updated
      
      ![image](https://user-images.githubusercontent.com/57001890/214602019-5b313113-d796-4233-ba26-25f9655df266.png)

  - uptime
  
      ![image](https://user-images.githubusercontent.com/57001890/214602221-d4fc68ca-ee9e-4e38-b12a-f3fcc3321d5a.png)
