### ISSUE TITLE
Improve the graphql processor chart

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/tfchain_graphql#8]
- [ ] environment variables configmap should not be named "env"
- [ ] selector labels
  - [ ] Deployments
    - [ ] processor
    - [ ] query-node
    - [ ] db 
  - [ ] configmap
- [ ] db host should come from within the chart itself
- [x] Create a pv(c) for the db if no pvc supplied
- [ ] rename ingresstest since the name does not state the purpose
- [ ] get rid of the kompose references

**Comment by DylanVerstraete** [comment]
We will be deprecating helm charts since we will move to other infra
