### ISSUE TITLE
Allow free & used IP sorting

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfchain_graphql#83]
orderBy free & used IP is not available as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/40770501/212533818-fea9e0da-3b3a-41b1-aff1-19d93363f481.png)

Related issues: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/60

**Comment by sameh-farouk** [comment]
@zaelgohary What do you mean by "orderBy free & used IP"? 
If you want to filter by free IPs, you can use something like

```Graphql 
query MyQuery {
  publicIps(where: {contractId_eq: "0"}) { # or `contractId_not_eq` for showing only used IPs instead
    ip
    id
    contractId
    gateway
  }
}
```
if you want to list both free and used IPs but give priority to free to show first, then something like that can be used
```graphql
query MyQuery {
  publicIps(orderBy: contractId_ASC) { # or `contractId_DESC` for listing used IPs first
    ip
    id
    contractId
    gateway
  }
}
```

Does that solve the issue? If not, please elaborate.
