### ISSUE TITLE
Firesquid crashing on qanet

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#84]
It's progressing blocks but crashing after

```
indexer qa: {"level":5,"time":1673862465470,"ns":"sqd:substrate-ingest","err":{"length":249,"name":"error","severity":"ERROR","code":"08P01","hint":"the maximum message size can be configured using the sql.conn.max_read_buffer_message_size cluster setting","file":"encoding.go","line":"286","routine":"NewProtocolViolationError
```

**Comment by DylanVerstraete** [comment]
Proposed fix:

Attempt to insert too much data at once. Either try to reduce --write-batch-size, or likely better, to increase the value of mentioned setting.

SET CLUSTER SETTING sql.conn.max_read_buffer_message_size cluster = bigger_value

Use SHOW CLUSTER SETTING to get the current value.

**Comment by DylanVerstraete** [comment]
@coesensbert can you please execute this on the Qa net indexer db?

**Comment by DylanVerstraete** [comment]
First on devnet

**Comment by coesensbert** [comment]
`SET CLUSTER SETTING sql.conn.max_read_buffer_message_size = '32MiB';`

seems to have resolved the issue, applied on dev en qanet cockroach db's

**Comment by DylanVerstraete** [comment]
Also apply on testnet and mainnet please

**Comment by xmonader** [comment]
@coesensbert are we documenting this in an operational guide? and if yes can you please link it?
