### ISSUE TITLE
Node uptime event does not properly node updatedAt field

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#86]
Somehow on QAnet an uptime event does not properly set the timestamp of when this report received to the node object

**Comment by DylanVerstraete** [comment]
fixed in https://github.com/threefoldtech/tfchain_graphql/commit/f71488b2131fe0d390f281f54da2e1d357841c43

**Comment by A-Harby** [comment]
verified 
On Devnet:
all nodes are up without any problems
![image](https://user-images.githubusercontent.com/109473873/214607797-0811c1f0-36a1-4997-a830-ab869870a2c1.png)
also, the `createdAt`, `updatedAt`, and `uptime` fields work well as expected!
* Node 13 :
  ![image](https://user-images.githubusercontent.com/109473873/214608121-ee870541-f42f-44ca-839f-6e5e1e013eae.png)
  - created 
      ![image](https://user-images.githubusercontent.com/109473873/214608240-ae4e2823-f2a0-4555-a8ae-f18bac2186a6.png)
      ![image](https://user-images.githubusercontent.com/109473873/214608734-30fbee6f-1076-4628-8b6f-6aafe8be042d.png)
  - updated
      ![image](https://user-images.githubusercontent.com/109473873/214608377-e9a737a3-c76a-4614-8fad-cdd165305bb9.png)
  - uptime
     ![image](https://user-images.githubusercontent.com/109473873/214608467-2a1ffc76-0fd6-4272-8a41-65957494aad6.png)
     ![image](https://user-images.githubusercontent.com/109473873/214608588-e5662622-c0cc-41bc-b17d-3d86aee59840.png)

On qanet:
all nodes are up for a while without any problems
![image](https://user-images.githubusercontent.com/57001890/214600996-bd0d28f7-41f4-4e9f-806a-194b3b3375d6.png)
also, the `createdAt`, `updatedAt`, and `uptime` fields work well as expected!
* Node 2 :
  - created 
      ![image](https://user-images.githubusercontent.com/57001890/214601734-a3443fd8-02b6-4937-b309-6f765a2f2693.png)
  - updated
      ![image](https://user-images.githubusercontent.com/57001890/214602019-5b313113-d796-4233-ba26-25f9655df266.png)
  - uptime
      ![image](https://user-images.githubusercontent.com/57001890/214602221-d4fc68ca-ee9e-4e38-b12a-f3fcc3321d5a.png)
