### ISSUE TITLE
Online nodes resources are null

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#87]
Need to figure out why this happens, I think an update call hasn't fetched node resources and inserts a null value

**Comment by A-Harby** [comment]
Verified.
On Devnet all node have resource and empty nodes aren't shown now. 
![image](https://user-images.githubusercontent.com/109473873/215754493-ad959bcb-504a-408c-b7f7-902a0e5360d2.png)
 And also same was verified on Qanet.
