### ISSUE TITLE
Do you need g++, make and python3 ?

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/tfchain_graphql#89]
In the dockerfile, a stage `node-with-gyp` is built with g++, make and python3.
Is this required?

**Comment by DylanVerstraete** [comment]
It's taken for the template repo so I guess yes https://github.com/subsquid/squid-substrate-template/blob/main/Dockerfile

**Comment by DylanVerstraete** [comment]
I tried building without this step, seems to be working. But I asked in their developer channel why this was included in the first place. Don't want to remove it without knowing first.

**Comment by xmonader** [comment]
@robvanmieghem should we close?

**Comment by robvanmieghem** [comment]
It's not necessary so I think it should be removed from the Dockerfile
