### ISSUE TITLE
node public config is not syncing properly 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfchain_graphql#94]
On node 73 in Dev net.

Trying to remove public config of a node. it got removed on the chain but graphql still shows the old values. Only the `domain` level is deleted.

Adding public config with `none` options to remove it.
![image](https://user-images.githubusercontent.com/32527347/220899161-89878d02-2231-41a9-a7d3-f58f475f39ea.png)

Checking the data on the chain. `null` as expected
![image](https://user-images.githubusercontent.com/32527347/220899536-c159d38f-38e6-4088-a3b4-fd36f1ee201e.png)

but graphql still shows the old values. only the `domain` is deleted.
![image](https://user-images.githubusercontent.com/32527347/220899863-970b9de6-0e25-4b3d-aa54-c18b48e63378.png)

Similar thing happens in case of updating a field and removing the other.

Updating only `ipv4`. so `ipv6` and `domain` should be `null`.
![image](https://user-images.githubusercontent.com/32527347/220900991-e0237285-aa3f-458c-a3dc-6957e05c2cd0.png)

on the chain
![image](https://user-images.githubusercontent.com/32527347/220901150-c1765ca2-8cd0-4354-a9e3-281a038b0dd1.png)

but graphql sill shows the old values
![image](https://user-images.githubusercontent.com/32527347/220901311-eae88161-f469-42d4-9c2d-2ba995ec6c02.png)

while syncing could the processor check the `null` values on the chain and set it to the equivalent zero values on the db?

**Comment by xmonader** [comment]
@DylanVerstraete please make sure to create an operational issue

**Comment by xmonader** [comment]
@Omarabdul3ziz Please expand with more details, what environment are you working against ?

**Comment by Omarabdul3ziz** [comment]
it was dev net. updated the original comment

**Comment by DylanVerstraete** [comment]
Thanks for reporting, will take a look!

**Comment by DylanVerstraete** [comment]
Fixed in v2.9.0-rc6, created an issue to deploy on devnet: https://github.com/threefoldtech/tf_operations/issues/1472

**Comment by DylanVerstraete** [comment]
I might need to create a patch version for testnet/mainnet

**Comment by A-Harby** [comment]
Verified on devnet.
Node ID 69 public config.
![image](https://user-images.githubusercontent.com/109473873/223133794-a987d728-ee27-42e4-8057-1f6cce8ca875.png)
After only changing IPV4 and GW4.
![image](https://user-images.githubusercontent.com/109473873/223134316-654b376e-fab2-4ce7-a03e-d973f09c10aa.png)
Graphql data was all null except IPV4 and GW4
![image](https://user-images.githubusercontent.com/109473873/223134366-3114d7a2-0218-4738-89f0-c443cd66f579.png)
