### ISSUE TITLE
Index TFT price

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfchain_graphql#98]
Index event: https://github.com/threefoldtech/tfchain/blob/bb09e8e88cbc055a89057d4bc084014c66fdd1a4/substrate-node/pallets/pallet-tft-price/src/lib.rs#L98

**Comment by LeeSmet** [comment]
Bump, also the average price stored. One use case is to check the actual historic cost of a contract in USD, by querying the bill reports for a contract and multiplying with the average price at the time of billing.

**Comment by sameh-farouk** [comment]
## Update
I think it makes sense to index the `averagePriceStored` event, as Lee suggested.

### Work Completed:
- index `averagePriceStored` Events.
### Work Remaining:
- index `priceStored` Events.

I ran into an issue with the `priceStored` event. The price was stored at older runtimes in `U16F16` encoded format as hex.
I'll go through its implementation to see how I should decode the `U16F16` hex value in JS to be indexed as a number instead.

Remaining Time: 1-2 days.

Resources: 
  - https://docs.rs/fixed/latest/fixed/types/type.U16F16.html
  - https://github.com/encointer/substrate-fixed
  - and https://github.com/encointer/encointer-js/tree/master/packages/util, which has a parser for `I32F32` (which closest thing I found).
